server:
    port: 8086
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: mahboob@2001
        url: jdbc:mysql://localhost:3306/orderservice?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
        show-sql: true
    application:
      name: ORDER-SERVICE
       
         
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8762/eureka}
